name: Deploy to AWS EC2

on:
  push:
    branches: [ "deploy" ]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::082228066340:role/GitHubDeployRole
          aws-region: ap-south-1

      - name: SSH Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd withprana-backend
            git pull origin deploy
            npm install
            npm run build
            pm2 restart 0 || pm2 start index.js --name app
